TodoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/urls.py
from django.urls import path, include
from base import views
from django.contrib.auth.views import LogoutView


app_name = 'base'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='base:login'), name='logout'),
    path('register_account/', views.RegisterAccount.as_view(), name='register_account'),

    path('', views.TaskList.as_view(), name='task_list'),
    path('task/<int:pk>', views.TaskDetail.as_view(), name='task_detail'),
    path('create-task/', views.TaskCreate.as_view(), name='create_task'),
    path('edit/<int:pk>', views.TaskUpdate.as_view(), name='edit-task'),
    path('delete-task/<int:pk>', views.TaskDelete.as_view(), name='task-delete'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['completed']

base/views.py
from django.shortcuts import render, redirect, reverse
from base.models import Task
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


# Create your views here.
class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:task_list')


class RegisterAccount(FormView):
    form_class = UserCreationForm
    template_name = 'base/register.html'
    success_url = reverse_lazy('base:task_list')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterAccount, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(reverse('base:task_list'))
        return super(RegisterAccount, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'task_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_list'] = context['task_list'].filter(user=self.request.user)
        context['count'] = context['task_list'].filter(completed=False).count()

        search_input = self.request.GET.get('search') or ''
        if search_input:
            context['task_list'] = context['task_list'].filter(title__startswith=search_input)
        context['search_input'] = search_input

        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description']
    template_name = 'base/task_form.html'
    success_url = reverse_lazy('base:task_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'completed']
    success_url = reverse_lazy('base:task_list')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('base:task_list')

base/templates/base/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
    <title>To Do App</title>
    <link rel="stylesheet" href="{% static 'base/style.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>

base/templates/base/login.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="header-bar">
        <h2>Login</h2>
    </div>

    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit">Login</button>
        </form>
        <p>Don't have an account? <a href="{% url 'base:register_account' %}">Register</a></p>
    </div>
{% endblock %}

base/templates/base/register.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="header-bar">
        <h2>Register an account</h2>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit">Login</button>
        </form>

        <p>Already have an account? <a href="{% url 'base:login' %}">Login</a></p>
    </div>
{% endblock %}

base/templates/base/task_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="header-bar">
        <a href="{% url 'base:task_list' %}">&#8592; Back</a>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <p>Do you want to delete your task?</p>
            <button class="button" type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

base/templates/base/task_detail.html
<h2>Detail task</h2>
<h3>{{ task.title }}</h3>
<p>{{ task.description }}</p>
<br>
<p>Completed? {{ task.completed }}</p>

base/templates/base/task_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="header-bar">
        <a href="{% url 'base:task_list' %}">&#8592; Back</a>
    </div>

    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit">Create</button>
        </form>
    </div>


{% endblock %}

base/templates/base/task_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="header-bar">
        <div>
            <h1>Hi, {{request.user|title}}</h1>
            <h2 style="margin: 0">You have {{count}} uncompleted task{{ count|pluralize:"s"}}.</h2>
        </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'base:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'base:login' %}">Login</a>
        {% endif %}
    </div>


    <div id="search-add-wrapper">
        <form class="search-form" method="GET">
            <input id="search-input" type="text" name="search" value="{{ search_input }}">
            <input class="button" type="submit" value="Search" id="search-bar">
        </form>
        <a id="create_task" href="{% url 'base:create_task' %}">Create Task</a>
    </div>


    <div class="task-items-wrapper">
        {% for task in task_list %}
            <div class="task-wrapper">
                {% if task.completed %}
                    <div class="task-title">
                        <div class="task-completed-icon"></div>
                        <i><s><a href="{% url 'base:edit-task' task.id %}">{{task}}</a></s></i>
                    </div>
                    <a class="delete-link" href="{% url 'base:task-delete' task.id %}">&#215;</a>
                {% else %}
                    <div class="task-title">
                        <div class="task-uncompleted-icon"></div>
                        <a href="{% url 'base:edit-task' task.id %}">{{task}}</a>
                    </div>
                    <a class="delete-link" href="{% url 'base:task-delete' task.id %}">&#215;</a>
                {% endif %}
            </div>
        {% empty %}
            <h3 id="no-task-info">No tasks in the list.</h3>
        {% endfor %}
    </div>
{% endblock %}